language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - xbuild CI.proj
  - nunit-console ./src/AndroidDeviceConfig.Test/bin/Debug/AndroidDeviceConfig.Test.dll -exclude NotWorkingOnMono

