language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
 
script:
  - xbuild CI.proj
  - nunit-console ./AndroidDeviceConfig.Test/bin/Release/AndroidDeviceConfig.Test.dll -exclude NotWorkingOnMono

